version: "3.1"

services:
  mongo:
    container_name: cl_mongo
    build: ./docker/mongo
    restart: always
    ports:
      - "27017:27018"

networks:
  default:
    external:
      name: cl-dashboard
